name: Test Github Actions Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - beta
    paths:
      - .github/**/*

jobs:
  job1:
    name: 'Set output'
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.set-output.outputs.name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - id: set-output
        name: 'Run script'
        uses: ./.github/actions/output

  job2:
    name: 'Read output'
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Read output
        shell: bash
        run: echo ${{ needs.job1.outputs.name }}
